# This is a basic workflow to help you get started with Actions

name: Build using markata

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: install markata
        run: pip install markata

      - name: render project
        run: copier -d project_name="Markata Blog Starter" -d url="https://blog-starter.marka.dev" -d author_fullname="Waylon Walker" -d author_email="waylon@waylonwalker.com" -d author_twitter="'@_waylonwalker'" -d description="The official markata starter for creating blogs" -d python_package_import_name="markata_blog_starter" copy . example

      - name: build with markata
        working-directory: ./
        run: markata build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          # you can choose the target branch of your choice
          target_branch: prod-markata
          build_dir: example/markout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
